services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: flaskapi-dev-todo-app
    container_name: flaskapi-todo-app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: todo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - todo_db_data:/var/lib/postgresql/data/
volumes:
  todo_db_data:
